##Spring
spring:
  application:
    name: product-manager-api
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: sa
  ##JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ## H2 DATABASE
  h2:
    console:
      enabled: true
      path: /h2-console

## Swagger
springdoc:
  swagger-ui:
    path: /swagger

app:
  jwt:
    encryption-key: 4e5e6e7e8e9e0e1e2e3e4e5e6e7e8e9e0
    login-expiration : 604800000  # 1000 * 60 * 60 * 24 * 7
    issuer: product-manager-api
