##Spring
spring:
  application:
    name: product-manager-api
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: sa
  ##JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ## H2 DATABASE
  h2:
    console:
      enabled: true
      path: /h2-console

## Swagger
springdoc:
  swagger-ui:
    path: /swagger

